### ISSUE TITLE
License concern

### ISSUE THREAD

**Issue by ethanhs** [exaphaser/SharpJS#3]
Just wanted to alert you, I don't think you can license this work under the GPL.
- XAPParse: Microsoft Public License/Ms-PL (Andy Patrick)

I believe the MS-PL doesn't allow for code under it to be re-licensed, thus it conflicts with the GPL (which requires all code to re-licensed under the GPL).

Great project otherwise!

**Comment by 0xFireball** [comment]
Hmm, interesting. Thanks for letting me know. Actually, my project doesn't really need XapParse, so I will probably just remove it.

Thank you so much for bringing this to my attention.

**Comment by 0xFireball** [comment]
@ethanhs I have verified that XapParse isn't really needed, so I'll remove it. Thank you again for bringing this to my attention.
